# Generated by Django 3.2 on 2024-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0008_auto_20220713_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netbook',
            name='estado',
            field=models.CharField(choices=[('ok', 'ok'), ('Docente', 'Docente'), ('no funciona', 'no funciona'), ('bloqueada', 'bloqueada'), ('pendiente de revision', 'pendiente de revision'), ('pendiente migracion', 'pendiente migracion'), ('robada', 'robada')], default='pendiente de revision', max_length=30),
        ),
    ]
