# Generated by Django 3.2 on 2024-05-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0009_alter_netbook_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='imagen1',
            field=models.ImageField(blank=True, upload_to='informes'),
        ),
        migrations.AddField(
            model_name='informe',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to='informes'),
        ),
        migrations.AddField(
            model_name='informe',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to='informes'),
        ),
    ]
