# Generated by Django 3.2 on 2024-05-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app001', '0010_auto_20240514_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_incorporación', models.DateField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Rte', 'Rte'), ('Pedagogico', 'Pedagogico')], max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='escuela',
            name='referente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app001.profile'),
        ),
    ]
