# Generated by Django 3.2 on 2024-05-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0011_auto_20240514_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app001.profile'),
        ),
    ]
