# Generated by Django 3.2 on 2024-05-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0012_alter_escuela_referente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fecha_incorporación',
            new_name='fecha_incorporacion',
        ),
    ]
