# Generated by Django 3.2 on 2024-05-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0013_rename_fecha_incorporación_profile_fecha_incorporacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escuela',
            old_name='referente',
            new_name='responsable',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app001.profile'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('consulta', 'consulta'), ('modificacion', 'modificacion'), ('Baja', 'Baja')], max_length=100),
        ),
        migrations.AlterField(
            model_name='informe',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app001.profile'),
        ),
        migrations.AlterField(
            model_name='netbook',
            name='estado',
            field=models.CharField(choices=[('ok', 'ok'), ('Prestamo', 'Préstamo a docente'), ('no funciona', 'no funciona'), ('bloqueada', 'bloqueada'), ('pendiente de revision', 'pendiente de revision'), ('pendiente migracion', 'pendiente migracion'), ('robada', 'robada')], default='pendiente de revision', max_length=30),
        ),
        migrations.AlterField(
            model_name='netbook',
            name='estado_disco',
            field=models.CharField(choices=[('flasheado', 'flasheado'), ('sin flashear', 'sin flashear')], default='sin flashear', max_length=20),
        ),
        migrations.AlterField(
            model_name='netbook',
            name='estado_pila',
            field=models.CharField(choices=[('Cargada', 'Cargada'), ('pendiente_de_cambio', 'Pendiente de Cambio'), ('Cambiada', 'Cambiada')], default='agotada', max_length=20),
        ),
        migrations.AlterField(
            model_name='netbook',
            name='imagen_win',
            field=models.CharField(blank=True, default='original', max_length=50),
        ),
    ]
