# Generated by Django 3.2 on 2024-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0014_auto_20240514_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='cue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
