# Generated by Django 3.2 on 2024-05-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0015_alter_escuela_cue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netbook',
            name='estado_pila',
            field=models.CharField(choices=[('Cargada', 'Cargada'), ('pendiente_de_cambio', 'Pendiente de Cambio'), ('Cambiada', 'Cambiada')], default='Cargada', max_length=20),
        ),
    ]
