# Generated by Django 3.2 on 2024-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0016_alter_netbook_estado_pila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netbook',
            name='identificador',
            field=models.IntegerField(),
        ),
    ]
