# Generated by Django 3.2 on 2024-05-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0023_alter_netbook_identificador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='directivo',
            options={'verbose_name_plural': 'Directivos'},
        ),
        migrations.AlterModelOptions(
            name='escuela',
            options={'verbose_name_plural': 'Escuelas'},
        ),
        migrations.AlterModelOptions(
            name='informe',
            options={'verbose_name_plural': 'Informes'},
        ),
        migrations.AlterModelOptions(
            name='netbook',
            options={'verbose_name_plural': 'Netbooks'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
