# Generated by Django 3.2 on 2024-05-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0024_auto_20240514_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directivo',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='directivo',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
