# Generated by Django 3.2 on 2024-05-15 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0025_auto_20240514_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivo',
            name='escuela',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app001.escuela'),
        ),
    ]
