# Generated by Django 3.2 on 2024-05-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0026_alter_directivo_escuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivo',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app001.escuela'),
        ),
    ]
