# Generated by Django 3.2 on 2024-05-15 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0028_alter_escuela_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directivo',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='directivo',
            name='escuela',
        ),
        migrations.AddField(
            model_name='directivo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escuela',
            name='directivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app001.directivo'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('consulta', 'consulta'), ('modificacion', 'modificacion'), ('Baja', 'Baja')], max_length=20),
        ),
    ]
