# Generated by Django 3.2 on 2024-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0029_auto_20240515_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AlterField(
            model_name='escuela',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
