# Generated by Django 3.2 on 2024-06-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0030_auto_20240607_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='directivo',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='netbook',
            name='escuela',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Directivo',
        ),
        migrations.DeleteModel(
            name='Escuela',
        ),
        migrations.DeleteModel(
            name='Informe',
        ),
        migrations.DeleteModel(
            name='Netbook',
        ),
    ]
